name: Dom O'Connell

email: dom.oconnell@me.com
description: "Portfolio - Musings"

livein: "Newark, Nottinghamshire, England"

twitter: "domoconnell"
github: "domoconnell"

markdown: Kramdown
highlighter: true

